package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildInstagramPost'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildInstagramPost")) {
    expectSteps {
        script {
            name = "Install npm packages"
            scriptContent = "npm install"
        }
        script {
            name = "Run tests"
            scriptContent = "npm run test"
        }
        script {
            name = "Run Instagram post"
            scriptContent = """
                node --version
                node ./.build/index.js --publish=./releases/%build.number% --source=./src/post.json
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            enabled = false
            clearConditions()
        }
    }
}
